name: 📋 Generate Firmware and Device Matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "Generated build matrix"
        value: ${{ jobs.generate.outputs.matrix }}

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  generate:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - id: build
        run: |
          MATRIX=$(yq -o=json devices.yaml | jq -c '
            {
              include: [
                .devices[]
                | select(.status == "ACTIVE")
                | . as $dev
                | ["Client", "Hardware-Registration-and-Configuration"][]
                | {
                    application: .,
                    product_hex: $dev.product_hex,
                    product_id: $dev.product_id,
                    fqbn: (
                      $dev.board_fqbn + ":" + (
                        $dev.board_options | to_entries | map(.key + "=" + .value) | join(",")
                      )
                    ),
                    bootloader_addr: $dev.bootloader_addr,
                    partition_size_app: (
                      $dev.partition_scheme[]
                      | select(.label == "app0")
                      | .size
                    )
                  }
              ]
            }
          ')

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
